### ISSUE TITLE
Tag not save when server restart

### ISSUE THREAD

**Issue by scorninpc** [RefracDevelopment/SimpleTags#29]
Hello again!

I see the method to save tag only run [when player quit!](https://github.com/RefracDevelopment/SimpleTags/blob/main/src/main/java/me/refracdevelopment/simpletags/listeners/PlayerListener.java#L52)

But when server restart, `onQuit` are not fired, so the player don't save tag

On player change the tag `setTag()`, isn't the best place to save?

**Comment by Refrac** [comment]
I'll consider saving for both and possibly on plugin shutdown

**Comment by Refrac** [comment]
Hmm currently i only save on player quit and the /tags set command i'll add it to the menu too
