### ISSUE TITLE
Change tag when player is offline

### ISSUE THREAD

**Issue by scorninpc** [RefracDevelopment/SimpleTags#30]
Hey @Refrac, how are you?

First, sorry I can't help with the code these days

But i found a new problem:

My player is offline, so my vip finish and the vip plugin remove permission and run command to set tag back like `simpletags set neterita scorninpc`

![image](https://github.com/RefracDevelopment/SimpleTags/assets/2607849/885f55f4-d14f-4a54-b3b2-6740ddacbd69)

All runs fine. But when player login, the tag are not changed! 

I'm using mysql, and i see on database that's tag not change if player is offline

 i'll appreciate if you can do a look

**Comment by Refrac** [comment]
@scorninpc No worries I'll take a look more than likely i forgot to save it to the database in the code or something

**Comment by Refrac** [comment]
Hmm this issue might be difficult i'm saving it to the database idk why it won't work tho

**Comment by scorninpc** [comment]
I'm backing today, and can help a little more with code!

Anyway, you test with mysql? after run command to change tag in console of offline player, it's not change in phpmyadmin

![image](https://github.com/RefracDevelopment/SimpleTags/assets/2607849/a3f24140-4158-4840-bfc4-b48ce6e617a5)

![image](https://github.com/RefracDevelopment/SimpleTags/assets/2607849/2939bbea-a369-4637-a50b-8fa26e8ed454)

I'm be able to see the code at night (my night hahaha)

**Comment by scorninpc** [comment]
@Refrac , maybe this problem is abut offline mode, with AuthMe and/or FastLogin

Look my uuid

![image](https://github.com/RefracDevelopment/SimpleTags/assets/2607849/1c39a4ae-5fc2-4698-babb-c885e7de11db)

And look uuid that SimpleTags are getting

![image](https://github.com/RefracDevelopment/SimpleTags/assets/2607849/238d8e64-9af6-41cb-aa8a-482f11617656)

**Comment by scorninpc** [comment]
@re

**Comment by Refrac** [comment]
So your running a cracked minecraft network?

**Comment by scorninpc** [comment]
I don't have a server, I'm just a dev on some

**Comment by Refrac** [comment]
Ok
